version: "3"

services:
  db:
    image: postgres:10-alpine
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"

  app:
    env_file: .env
    build:
      context: .
    ports:
      - "8000:8000"
    command: sh -c "python manage.py test --verbosity 3"
    depends_on:
      - db
