# Generated by Django 3.1.7 on 2022-04-16 01:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorer', '0002_auto_20220415_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent_folder', 'owner')},
        ),
    ]
