# Generated by Django 3.1.7 on 2022-04-16 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import explorer.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorer', '0003_auto_20220416_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to=explorer.models.get_s3_file_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.folder')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'parent_folder', 'owner')},
            },
        ),
    ]
