# Generated by Django 3.1.7 on 2022-04-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
