version: "3"

services:

  db:
    image: postgres:10-alpine
    env_file: ../.env
    environment:
      - POSTGRES_DB=file_explorer_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword232323
    ports:
      - "5432:5432"

  caddy:
    env_file: ../.env
    image: caddy/caddy
    container_name: "caddy"
    hostname: "caddy"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  django:
    restart: unless-stopped
    env_file: ../.env
    expose:
      - 8000
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    command: sh -c "./wait_db.sh db:5432 --
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn my_file_explorer.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=file_explorer_db
      - DB_USER=postgres
      - DB_PASS=supersecretpassword232323
    depends_on:
      - db
