# Generated by Django 3.1.7 on 2022-04-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_auto_20220415_1931'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='root_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='explorer.folder'),
        ),
    ]
